### ISSUE TITLE
TwigExtension classes still in pretty-printer package

### ISSUE THREAD

**Issue by pyrech** [memio/pretty-printer#1]
Just a question, I may miss something but why the TwigExtension namespace is still present on this package? Shouldn't have it been removed when introducing the twig-template-engine package?

**Comment by gnugat** [comment]
Yes it should, I missed this one :( .

**Comment by gnugat** [comment]
Will be fixed in #4 (aiming at version `1.0.3`)

**Comment by gnugat** [comment]
Fixed, thanks for your contribution @pyrech
